version: '3'

services:
  # --- PostgreSQL Database ---
  postgres:
    image: postgres:17-alpine
    container_name: simple_postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- Redis Cache ---
  redis:
    image: redis:8-alpine
    container_name: simple_redis_cache
    restart: always
    ports:
      - "6379:6379" 
      
volumes:
  postgres_data: